sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: ep_<%= Rails.env %>

default: &default
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default

test:
  <<: *default
